# 指定使用的 CircleCI 版本
version: 2.1

jobs:
  # 编译任务
  build:
    docker:
      - image: circleci/node:latest
    steps:
      # 检出代码
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: npm install
      - run: npm run build
      - run: mv dist docker
      - run:
          name: 打包Docker
          command: |
            cd ./docker
            ls
            DATE=`date +%Y%m%d`
            DOCKER_IMAGE_VERSION=$DATE-0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_REPOSITORY:$DOCKER_IMAGE_VERSION .
            docker login -u $DOCKER_USER -p $DOCKER_PASS registry.cn-beijing.aliyuncs.com
            docker push $DOCKER_REPOSITORY:$DOCKER_IMAGE_VERSION

workflows:
  version: 2
  build_docker:
    jobs:
      - build:
          filters:
            branches:
              only: master
